// Code generated by "stringer -type=RLBotCoreStatus"; DO NOT EDIT.

package status

import "strconv"

const _RLBotCoreStatus_name = "SuccessBufferOverfilledMessageLargerThanMaxInvalidNumPlayersInvalidBotSkillInvalidHumanIndexInvalidNameInvalidTeamInvalidTeamColorIDInvalidCustomColorIDInvalidGameValuesInvalidThrottleInvalidSteerInvalidPitchInvalidYawInvalidRollInvalidPlayerIndexInvalidQuickChatPresetInvalidRenderTypeQuickChatRateExceededNotInitialized"

var _RLBotCoreStatus_index = [...]uint16{0, 7, 23, 43, 60, 75, 92, 103, 114, 132, 152, 169, 184, 196, 208, 218, 229, 247, 269, 286, 307, 321}

func (i RLBotCoreStatus) String() string {
	if i < 0 || i >= RLBotCoreStatus(len(_RLBotCoreStatus_index)-1) {
		return "RLBotCoreStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RLBotCoreStatus_name[_RLBotCoreStatus_index[i]:_RLBotCoreStatus_index[i+1]]
}
